### ISSUE TITLE
PMD 6.0.0 update

### ISSUE THREAD

**Issue by rsoesemann** [codacy/codacy-pmdjava#43]
The PMD maintainers asked how to make sure that Codacy is able to timely update their PMD version when 6.0 is out here: https://github.com/pmd/pmd/issues/709

Is there anything I can tell them? How fast can you do it and do you see any obstacles with integrating 6.0 into your existing plugin? Feel free directly jump into the above mentioned issue.

**Comment by rtfpessoa** [comment]
Is there anything special about this release?
From our side it should be a quick update.

**Comment by rtfpessoa** [comment]
After a quick look, I noticed a couple of details:
* After trying to use the `6.0.0-SNAPSHOT` seems like `apex-jorje-shaded` is missing? Anything changes or is this just a SNAPSHOT detail? (To skip this problem I used the `apex-jorje-shaded` from `5.8.1` and I was able to check the code)
* Seems like `RulesetsFactoryUtils.getRulesetFactory` changed and now needs a `ResourceLoader`, @adangel can you check https://github.com/codacy/codacy-pmdjava/blob/master/src/main/scala/codacy/pmd/PMD.scala#L52 and maybe give me a hint of what I should change?

**Comment by jsotuyod** [comment]
@rtfpessoa let me answer that for you

> * After trying to use the 6.0.0-SNAPSHOT seems like apex-jorje-shaded is missing?

PMD 6.0.0 upgrades to the latest jorje version. This one is more modular, and ceases to require some dependencies. The jars you would need now are:

* apex-jorje-data-1.0-sfdc-224-SNAPSHOT-3083815933
* apex-jorje-ide-1.0-sfdc-224-SNAPSHOT-3083815933
* apex-jorje-parser-1.0-sfdc-224-SNAPSHOT-3083815933
* apex-jorje-semantic-1.0-sfdc-224-SNAPSHOT-3083815933
* apex-jorje-services-1.0-sfdc-224-SNAPSHOT-3083815933
* apex-jorje-tools-1.0-sfdc-224-SNAPSHOT-3083815933
* guava-22.0
* asm-6.0.jar

Notice, we are still unsure if the jorje-ide and jorje-tools ones are actually needed at runtime, these may be dropped before the final release.

> Seems like `RulesetsFactoryUtils.getRulesetFactory` changed and now needs a `ResourceLoader`

Yes, I introduced this change. Since Apex doesn't use the auxclasspath, using a [new default instance of `ResourceLoader`](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/util/ResourceLoader.java#L38) should be enough. Just pass a `new ResourceLoader()` along.

**Comment by rtfpessoa** [comment]
@jsotuyod thanks for the help. Will make the changes now and see if everything else is ok.

Created #44 to keep track of the progress.

**Comment by up2go-rsoesemann** [comment]
@rtfpessoa PMD 6.0.0 is out. In case you need help integrating it please eighter comment here or add an issue in the PMD repo itself.

Everybody is eager to use the latest PMD rules in our repos :-)

**Comment by rtfpessoa** [comment]
Sorry for the delay here, but since this is a big change product needs to prfioritize this.

We did not have `ref` support and since all the rules changed this would break all people using the UI.

**Comment by up2go-rsoesemann** [comment]
Any updates?! Not being able to run the latest PMD in Codacy is a bad thing for a company that is paying basically just for that.

**Comment by rtfpessoa** [comment]
@up2go-rsoesemann, sorry for this delay.

To be completely honest, the main problem is about updating tools without breaking old users. Support was receiving complaints about projects stopping to analyse after updates and until we have a final solution we are holding updates.

To be fair, the problem is not related to PMD directly since it supports references but with most tools in general. I checked with product and this is scheduled to be discussed next week and we should have a long term solution soon.

We hope to have fast future releases and even better support for users that prefer the UI vs configuration files.

**Comment by up2go-rsoesemann** [comment]
@rtfpessoa thanks for your kind and honest answer. I absolutely appreciate this. Your boss also contacted me via Twitter an I know you guys are working on this. I will try to support you wherever I can.

**Comment by rsoesemann** [comment]
Any updates here?

**Comment by lara-silva** [comment]
@rsoesemann hi! Sorry for the time it took but we finally had the discussion and defined a plan to support tool updates in a more systematic way. Having that into consideration we will be working on your tool update on the next sprint - we should expect a release between 6 to 9 February (1st week of our next sprint). 

We will get back to you once this is live! Thanks once again!

**Comment by rsoesemann** [comment]
You guys rock. Please tell if and when I can support you.

**Comment by rsoesemann** [comment]
PMD 6.1.0 was just released: https://github.com/pmd/pmd/releases/tag/pmd_releases%2F6.1.0

**Comment by rtfpessoa** [comment]
Hi @rsoesemann,
We just added support for PMD 6.1.
However, due to the way Codacy currently works and the changes to the PMD rulesets, we are making it available as a standalone engine.
This means that to get PMD 6.1 on your projects, you'll have to disable the old PMD version and enabled the new one.

Please note, that for projects without configuration file, this also means that you'll lose the respective enabled patterns configuration.
We are aware that this is not the best use case, and we're working (that's why we delayed this update for so long) on improving it for future updates.

Thanks for your patience and support!

**Comment by rsoesemann** [comment]
Thanks Codacy for making this happen. PMD 6 is a big improvement. Having 2 PMD engines is not perfect but I understand why you had to do this. 

1. Will the new PMD 6 engine allow me to have custom rulesets in my repo?
2. Which files does it need? Now that everything is split into category files?
3. What is you long term roadmap for PMD support?
4. How can I (with my PMD contacts and my Apex knowledge) support you getting there faster?

**Comment by rtfpessoa** [comment]
> Will the new PMD 6 engine allow me to have custom rulesets in my repo?
 Not sure if this is what you mean but everything that works on the old PMD should work now plus new patterns.
Also, we read the config files with names: "ruleset.xml" and "apex-ruleset.xml"

> Which files does it need? Now that everything is split into category files?
If you provide a ruleset.xml with the `ref` property should be enough.

> What is you long term roadmap for PMD support?
We now have a plan for engines to support multiple versions (like PMD 5 and 6) and to have faster updates. This needs a bit of development but we will keep you updated as we go.

> How can I (with my PMD contacts and my Apex knowledge) support you getting there faster?
At the moment your support has been amazing to keep this going, and specially to have Apex in the first place.
Now most of the work needs to be done internally, to assure the versions coexist fine and that upgrading is smooth for everybody. Will follow up with an email to see if you can help more in the contacts part.

Thanks for your support @rsoesemann!
